name: ml-blackjack
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=12.1
  - jupyterlab
  - ipykernel
  - pip
  - pip:
    - stable-baselines3
    - gymnasium[all]